### ISSUE TITLE
The program {} has exited with code -1073740940 (0xc0000374).

### ISSUE THREAD

**Issue by uno-studio** [Fusion86/ScrcpyNet#1]
I got this error when I tried the sample program. No exceptions are thrown. Can you check the cause of this error?

**Comment by Fusion86** [comment]
While I would not recommend anyone to use this crappy proof-of-concept, it still shouldn't crash on startup.
What exactly are you doing? I can't replicate the issue on my end.

Before starting this program you should start the adb daemon manually, you can do this by running `adb devices` in cmd.
![image](https://user-images.githubusercontent.com/4460428/114620342-c5fd8900-9cab-11eb-9078-38d1bcba405d.png)

I guess you could try running that command before starting the sample application? It shouldn't really crash, but this would be my first guess.

Also, are you running it through visual studio, or some other way?

**Comment by Fusion86** [comment]
Actually, that probably isn't the problem.

You'll need to manually install de ffmpeg binaries and the `scrpy-server.jar` file. These files should be in the same folder as the `ScrcpyNet.Avalonia.Sample.exe` file.

 **FFMPEG**
You can download the ffmpeg binaries from [here](https://www.gyan.dev/ffmpeg/builds/). You need the `ffmpeg-release-full-shared.7z` file. Extract all files .dll from the `bin` folder in the application root.

**scrcpy-server.jar**
You'll need to download the `scrcpy-server-v1.17` file from [here](https://github.com/Genymobile/scrcpy/releases/tag/v1.17). Rename this file to `scrcpy-server.jar` and place it in the application root.

Example:
I couldn't fit all .dlls in this screenshot (e.g. swscale-5.dll), but you also need those. So make sure to extract all .dll files from the bin directory inside xxx-release-full-shared.7z.
![image](https://user-images.githubusercontent.com/4460428/114621567-24773700-9cad-11eb-811c-ad48a352e9ab.png)

Sorry that I didn't put this in the readme :|
Please do report back if this fixed your issue.

P.s. the Avalonia frontend is quite crappy, but I believe this is also because of some bugs inside Avalonia (frames don't feel 'smooth' and sometimes it crashes).

**Comment by uno-studio** [comment]
I also used sharpadbclient, started up adbserver, and use device get by sharpadbclient, with adb everything was fine. I ran through visual studio 2019

I have included ScrcpyNet and ScrcpyNet.Avalonia in my project and edited the paths into a separate directory. I debug and see ScrcpyNet has successfully started the scrcpy server. even when I am not using ScrcpyNet.Avalonia, the program still exits with the code as header after successfully starting the scrcpy server for a few seconds.
![14-04-2021_04-52-13](https://user-images.githubusercontent.com/43975116/114626917-94ea7c00-9cde-11eb-921c-ab7938d48321.png)
![14-04-2021_04-52-36](https://user-images.githubusercontent.com/43975116/114626921-961ba900-9cde-11eb-81a9-2bc80014c7ed.png)
![14-04-2021_05-02-22](https://user-images.githubusercontent.com/43975116/114626971-ab90d300-9cde-11eb-85c7-d7e52d4ffc1c.png)

**Comment by Fusion86** [comment]
What happens when you place all the files next to your .exe, remove all `ffmpeg.RootPath` lines, and reset `ScrcpyServerFile` to `"scrcpy-server.jar"`?

If it still crashes (without showing the debugger in visual studio) you could take a look at the Windows Logs -> Application inside the Windows Event Viewer.
The event viewer should show two errors. One is a generic error, and one is a .NET Runtime error. You should look at the .NET error content (and paste it here if needed).
![image](https://user-images.githubusercontent.com/4460428/114628039-8b4d1e00-9cb6-11eb-9e86-6685ebd916d2.png)

**Comment by uno-studio** [comment]
******Update******
`You can download the ffmpeg binaries from here. You need the ffmpeg-release-full-shared.7z file. Extract all files .dll from the bin folder in the application root.`
this worked, it needed all dll and exe files from ffmpeg-release-full-shared.7z so the program wouldn't close

however, I still cannot get the image of the device on the interface. i am having more error
```
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
```

I will check and report back later, thanks very much

**Comment by Fusion86** [comment]
Hmm, I have those errors too but it works fine otherwise.
```
[00:31:12 INF] Starting scrcpy server...
[00:31:12 INF] Start command: CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.17 debug 0 8000000 0 -1 false - true true 0 false false - -
[00:31:13 INF] Video socket connected.
[00:31:13 INF] Control socket connected.
[00:31:13 INF] Device name: SM-G970F
[00:31:13 INF] 1080x2280
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
```

You can always double check with the official scrcpy to make sure that its not an issue with your phone/device.

You can also use logcat to check if everything is working on your device:
```sh
# For Windows
adb -d logcat | findstr scrcpy

# For Linux
adb -d logcat | grep -i scrcpy
```

On my Samsung S10e it looks like this:
```
04-14 00:34:28.159 25374 25374 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
04-14 00:34:28.161 25374 25374 I scrcpy  : Device: samsung SM-G970F (Android 11)
04-14 00:34:28.228 25374 25374 D scrcpy  : Using encoder: 'OMX.Exynos.AVC.Encoder'
04-14 00:34:28.440 25388 25388 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.CleanUp
04-14 00:34:44.892 25374 25390 D scrcpy  : Controller stopped
04-14 00:34:45.943 25388 25388 I scrcpy  : Cleaning up
04-14 00:34:45.948 25388 25388 I scrcpy  : Restoring normal power mode
```

On my Huawei tablet I get an `app_process: Failed execv(/system/bin/dex2oat...` error, but you can ignore those.

The decoder is hardcoded to use `AV_CODEC_ID_H264`, maybe if your phone is not using an AVC encoder (like `OMX.Exynos.AVC.Encoder` or `OMX.hisi.video.encoder.avc`) it can't decode the frames?

**Comment by uno-studio** [comment]
I am experimenting with LDPlayer emulator, it works fine when I use original scrcpy.exe

the truth is I don't need to transmit frames and displays. i am trying to use touch commands to send faster than adb to build android automation program. I find your project partially tailored to my needs. maybe I'll customize and remove the real-time visual rendering and focus on sending custom commands like touch, swipe, take a single screenshot, or dump the xml layout if possible

**Comment by Fusion86** [comment]
Ah I see.
You could remove the following in [ScrcpyNet/Scrcpy.cs](https://github.com/Fusion86/ScrcpyNet/blob/master/src/ScrcpyNet/Scrcpy.cs#L44). By leaving VideoStreamDecoder as null it'll not call the Decode function [here](https://github.com/Fusion86/ScrcpyNet/blob/master/src/ScrcpyNet/Scrcpy.cs#L204).
```csharp
// Remove these two lines
VideoStreamDecoder = videoStreamDecoder ?? new VideoStreamDecoder();
VideoStreamDecoder.Scrcpy = this;
```

The touch input part is handled in [ScrcpyNet.Avalonia/ScrcpyDisplay.cs](https://github.com/Fusion86/ScrcpyNet/blob/master/src/ScrcpyNet.Avalonia/ScrcpyDisplay.cs), so you could copy/paste that. A simple touch is handled inside `OnPointerPressed` (which calls `SendTouchCommand`).

And if you need infrequent frames (aka not real-time) then requesting those using ADB should be fine too.

E: I guess I'm going to close this issue now. If you need anything else feel free to reopen it or create a new one.

**Comment by uno-studio** [comment]
Thanks for the suggestion, I found it and I'm working on it. Have a nice day
