### ISSUE TITLE
WPF Support?

### ISSUE THREAD

**Issue by waylaa** [Fusion86/ScrcpyNet#4]
Will there be any WPF support?

**Comment by Fusion86** [comment]
For which version would you like WPF support? For (legacy) .NET Framework or .NET Core (and .NET 5.0)?

**Comment by waylaa** [comment]
.NET Core especially .NET 6

**Comment by Fusion86** [comment]
I created a basic WPF implementation and a [sample application](https://github.com/Fusion86/ScrcpyNet/tree/master/src/ScrcpyNet.Sample.Wpf). ~It currently only supports mouse/touch input. No keyboard input yet because for some reason OnKeyDown doesn't fire. That is something I'll look at sometime later.~ Fixed, but mouse and keyboard work.

The WPF version might be unstable, but it seems to work okay-ish on my pc. Performance seems 'good enough' for now too.

I also haven't managed to create a nuget package yet. For some reason this is pretty difficulty with external dependencies, or maybe I'm just missing something.

I hope to have all issues fixed sometime this week. If you find any other issues or have other feature requests, please feel free to share them.

**Comment by Fusion86** [comment]
Alright so I published two packages, [ScrcpyNet ](https://www.nuget.org/packages/ScrcpyNet/)and [ScrcpyNet.Wpf](https://www.nuget.org/packages/ScrcpyNet.Wpf/), which implement the basic functionality. If you need some other feature or find a bug then please create a new issue 👍
